### ISSUE TITLE
Allow saving files with custom file extensions

### ISSUE THREAD

**Issue by eduherminio** [RaulPascual/BlocDeNotas#3]
When saving a file, it is always given `.txt` extension.
It would be interesting to allow saving them as `.java`, `.cpp`, `.cs`, `.html`, etc.

Example: When trying to save `FileName.java`, it gets save as `FileName.java.txt`.

![image](https://user-images.githubusercontent.com/11148519/63373487-ef073280-c37f-11e9-97c6-7bf90a2fd10b.png)

PD: When saving it as `FileName.txt`, it ends up as `FileName.txt.txt` too.

**Comment by RaulPascual** [comment]
Done!
